version: "3.8"

services:
  mysql:
    container_name: mysql_appbuscalo
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: app_buscalo
      MYSQL_USER: buscalo
      MYSQL_PASSWORD: 2345
    volumes:
      - mysqlappbuscalo:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mysqlappbuscalo
    restart: unless-stopped

  phpmyadmin:
    container_name: phpmyadmin_appbuscalo
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8082:80"
    networks:
      - mysqlappbuscalo
    restart: unless-stopped
  java_app:
    container_name: java_appbuscalo
    image: buscalo-java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - MYSQL_CONN=jdbc:mysql://mysql_appbuscalo:3306/app_buscalo
      - MYSQL_DB_USERNAME=buscalo
      - MYSQL_DB_USER_PASS=2345
    depends_on:
      - mysql
    networks:
      - mysqlappbuscalo

networks:
  mysqlappbuscalo:
    driver: bridge

volumes:
  mysqlappbuscalo:
