spring:
  application:
    name: buscalo-product-api
  datasource:
    url: ${MYSQL_CONN}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_USER_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
  sql:
    init:
      mode: always
      schema-locations: classpath:bd/tablas.sql
      data-locations: classpath:bd/data.sql
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        hbm2ddl.auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 8080
